/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import org.example.models.CelsiusToFahrenheit;
import org.example.models.FahrenheitToCelsius;
import org.example.models.TempConverterI;

import java.util.InputMismatchException;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Para qual escala de temperatura converer? (F ou C):");

        try {
            String escala = scanner.nextLine();
            if(!escala.matches("^[CF]$")) {
                throw new RuntimeException();
            }
            TempConverterI converter;
            if(escala.equals("C")) {
                converter = new FahrenheitToCelsius();
            } else {
                converter = new CelsiusToFahrenheit();
            }


            System.out.println("Temperatura na unidade base:");
            Float temp = scanner.nextFloat();

            System.out.printf("A temperatura informada, convertida, fica: %.2f %s", converter.convert(temp), escala);
        }catch (InputMismatchException ex) {
            System.out.println("O conteúdo digitado não é compatível com o formato esperado.");
        }
        catch (Exception ex) {
            System.out.println("ERRO! Você deve informar o valor C para Celsius ou F para Fahrenheit");
        }
    }
}
